import type { FlagBag, OwnedRecord, ResourceBag, SceneKey, Vector2 } from './common.ts';
import type { GearMod, PlayerGear } from './catalog.ts';
import type { ProficiencyState } from './proficiency.ts';

export interface ActorState extends OwnedRecord, Vector2 {
  kind?: string;
  actorType?: string;
  name?: string;
  relationId?: string;
  species?: string;
  faction?: string;
  region?: string;
  r?: number;
  color?: string;
  hp?: number;
  maxHp?: number;
  mp?: number;
  maxMp?: number;
  stamina?: number;
  atk?: number;
  def?: number;
  speed?: number;
  alive?: boolean;
  cooldown?: number;
  cooldownTimer?: number;
  specialClock?: number;
  playerAggro?: number;
  petAggro?: Record<string, number>;
  slowTimer?: number;
  slowPower?: number;
  arrowHits?: number;
  guard?: boolean;
  ranged?: boolean;
  pounce?: boolean;
  flee?: boolean;
  split?: boolean;
  slimeGen?: number;
  wounded?: boolean;
  wantsTalk?: boolean;
  lastTalk?: number;
  affection?: number;
  devotion?: number;
  [key: string]: unknown;
}

export interface PlayerState extends ActorState {
  id: string;
  ownerId: string;
  partyId: string;
  control: string;
  actorType: 'player';
  x: number;
  y: number;
  r: number;
  hp: number;
  maxHp: number;
  baseMaxHp: number;
  mp: number;
  maxMp: number;
  baseMaxMp: number;
  stamina: number;
  gold: number;
  herbs: number;
  potions: number;
  arrows: number;
  rings: number;
  wood: number;
  stone: number;
  resources: ResourceBag;
  atk: number;
  def: number;
  race: string;
  job: string;
  proficiency: ProficiencyState;
  weapon: string;
  gear: PlayerGear;
  gearBag: string[];
  gearMods: Record<string, GearMod[]>;
  materials: ResourceBag;
  magicKnown: string[];
  magicClues: FlagBag;
  mpRegenLock: number;
  monsterForm: boolean;
  originalRace: string | null;
  corruption: number;
  corruptionHitCooldown: number;
  corruptionStageWarnings: FlagBag;
  corruptionChoicePending: boolean;
  corruptionRampageWarningTimer: number;
  corruptionRampageTimer: number;
  corruptionRampageAttackCooldown: number;
  reversePotions: number;
  deathFatigue: number;
  deathFatigueReliefCooldown: number;
  spouse: string | null;
  conceptSword: boolean;
  lastHitBy: ActorState | null;
  invuln: number;
  attackCooldown: number;
  giftCooldown: number;
  portalCooldown: number;
  dodgeCooldown: number;
  dodgeTimer: number;
  blockTimer: number;
  running: boolean;
  runExhausted: boolean;
}

export interface PetState extends ActorState {
  id: string;
  petId?: string;
  name: string;
  x: number;
  y: number;
  hp: number;
  maxHp: number;
  alive: boolean;
  injured?: boolean;
  carried?: boolean;
  lost?: boolean;
  dead?: boolean;
  rescueTimer?: number;
  scene?: SceneKey;
  roamRadius?: number;
  guardRange?: number;
  attackRange?: number;
  cooldown?: number;
  cooldownTimer?: number;
  wanderTimer?: number;
  wanderX?: number;
  wanderY?: number;
}

export interface PetRemainState extends OwnedRecord, Vector2 {
  id: string;
  kind: 'corpse' | 'grave' | string;
  petName: string;
  scene: SceneKey;
  color?: string;
  age: number;
  decay: number;
  decayClock: number;
}
